import type { ImageSourcePropType } from "react-native"
import type { Ionicons } from "@expo/vector-icons"
import type { SongTheme } from "@/lib/theme"

export interface Song {
  id: number
  title: string
  /** Original (usually English) title the Albanian version is adapted from. */
  englishTitle?: string
  /** Colour identity for this song's page (see `songThemes`). */
  palette: SongTheme
  /** Content-matched icon used on the card and hero placeholder. */
  icon: keyof typeof Ionicons.glyphMap
  /** Optional illustration; songs without one show a coloured placeholder. */
  image?: ImageSourcePropType
  /** Optional link to the song video (opens externally). */
  videoUrl?: string
  lyrics: string[]
  /** Lyric fragments to emphasise (chorus / rhythmic hooks). */
  highlights?: string[]
  newWords?: { word: string; meaning: string }[]
  whatWeLearn?: string[]
  activity?: string
}

export const songs: Song[] = [
  {
    id: 1,
    title: "Kopshti im",
    palette: "apple",
    icon: "flower",
    videoUrl: "https://www.youtube.com/watch?v=qfMuE6y7G7Q",
    lyrics: [
      "Në kopshtin tim të bukur një lule unë kam mbjellë",
      "Nën diell me ujë e ajër lëshon të bukurën erë...",
      "",
      "Po një lule e vetme nuk mund të rrijë! E si mund të rrijë?",
      "E si mund të rrijë?",
      "",
      "Do të mbjell një lule tjetër, më pas",
      "Do të jenë dy!",
      "Do të jenë dy!",
      "",
      "Në kopshtin tim të bukur dy lule lulëzojnë,",
      "Diellin, ujin, ajrin ato i shijojnë!",
      "Shiko!",
      "Kur bashkë janë sa shumë gëzojnë, kur bashkë jetojnë",
      "Po ta mbjell edhe një tjetër, pastaj, më bëhen 3, më bëhen 3!",
      "",
      "Tri lule kopshtit tim i japin hijeshi!",
      "Dielli, uji, ajri i mbush me lumturi",
      "Lumturi x4",
    ],
    highlights: ["Lumturi", "Do të jenë dy"],
    newWords: [
      { word: "Kopsht", meaning: "vendi ku mbjellim lule e perime" },
      { word: "Lule", meaning: "bima e bukur me ngjyra" },
      { word: "Ajër", meaning: "fryma që marrim, s’e shohim" },
    ],
    whatWeLearn: ["Numërojmë 1, 2, 3", "Si rritet një lule: diell, ujë e ajër", "Sa bukur kur jemi bashkë"],
    activity: "Mbill një farë në një gotë dhe vizato si rritet çdo ditë.",
  },
  {
    id: 2,
    title: "Detari në det",
    palette: "instrument",
    icon: "fish",
    videoUrl: "https://www.youtube.com/watch?v=OOj2D4I2GxU",
    lyrics: [
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Ishte një shishe thellë në det, det, det",
      "",
      "Yll deti!",
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Ishte ylli i detit thellë në det, det, det",
      "",
      "Gaforre!",
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Ishte një gaforre thellë në det, det, det",
      "",
      "Kali i detit!",
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Ishte një kalë deti thellë në det, det, det!",
      "",
      "Peshku!",
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Ishte peshku që notonte në det, det, det!",
      "",
      "Oktapodi!",
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Ishte oktapodi që notonte në det, det, det!",
      "",
      "Peshkaqeni!",
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Një eshkaqen që notonte në det, det, det!",
      "",
      "Breshka!",
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Ishte një breshkë që notonte në det,det,det!",
      "",
      "Raxha!",
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Një peshk raxha që notonte në det, det, det!",
      "",
      "Kandil deti!",
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Një kandil që notonte në det, det, det!",
      "",
      "Delfini!",
      "Detari shkoi në det, det, det",
      "Të shohë çfarë mund të ketë, ketë, ketë",
      "Por ajo çfarë u gjet, gjet, gjet",
      "Një delfin që notonte në det, det, det!",
    ],
    highlights: ["det, det, det", "ketë, ketë, ketë"],
    newWords: [
      { word: "Detar", meaning: "ai që punon në det me anije" },
      { word: "Gaforre", meaning: "kafshë deti me gërshërë" },
      { word: "Oktapod", meaning: "kafshë deti me tetë krahë" },
    ],
    whatWeLearn: ["Kafshët e detit", "Rima: det – ketë – gjet", "Fjalë që përsëriten"],
    activity: "Rretho kafshët e detit që dëgjove në këngë.",
  },
  {
    id: 3,
    title: "BINGO",
    palette: "movement",
    icon: "paw",
    videoUrl: "https://www.youtube.com/watch?v=Ssdh_TUcBBY",
    lyrics: [
      "Na ish një fermer që kish një qen",
      "Dhe Bingo kishte emrin",
      "B-I-N-G-O x4",
      "Dhe Bingo kishte emrin!",
      "",
      "Na ish një fermer që kish një qen",
      "Dhe Bingo kishte emrin",
      "-, I-N-G-O x4",
      "Dhe Bingo kishte emrin!",
      "",
      "Na ish një fermer që kish një qen",
      "Dhe Bingo kishte emrin",
      "-,-, N-G-O x4",
      "Dhe Bingo kishte emrin!",
      "",
      "Na ish një fermer që kish një qen",
      "Dhe Bingo kishte emrin",
      "- - -G-O x4",
      "Dhe Bingo kishte emrin!",
      "",
      "Na ish një fermer që kish një qen",
      "Dhe Bingo kishte emrin",
      "- - - -O x4",
      "Dhe Bingo kishte emrin!",
    ],
    highlights: ["B-I-N-G-O", "Dhe Bingo kishte emrin"],
    newWords: [
      { word: "Fermer", meaning: "njeriu që punon në fermë me kafshë" },
      { word: "Qen", meaning: "kafsha besnike që leh" },
      { word: "Emër", meaning: "fjala me të cilën na thërrasin" },
    ],
    whatWeLearn: ["Shkronjat B-I-N-G-O", "Të shqiptojmë shkronjat", "Përsëritje me duartrokitje"],
    activity: "Shkruaj shkronjat B-I-N-G-O dhe thuaji me zë.",
  },
  {
    id: 4,
    title: "Lepurushi",
    palette: "nature",
    icon: "paw",
    videoUrl: "https://www.youtube.com/watch?v=AVUXlPGZULk",
    lyrics: [
      "Lepurush, lepurush, pse kaq shpejt vrapon në fushë?",
      "Lart në breg ku ka lule, me kërcim futet në shkurre!",
      "",
      "Po qenushi ta zë, kurrsesi s’duhet ta lë",
      "Vrap e vrap, me kërcim,  futet në pyllin pa kthim!",
      "x2",
    ],
    highlights: ["me kërcim", "Vrap e vrap"],
    newWords: [
      { word: "Lepur", meaning: "kafshë e vogël me veshë të gjata që kërcen" },
      { word: "Shkurre", meaning: "bimë e vogël e dendur" },
      { word: "Pyll", meaning: "vend me shumë pemë" },
    ],
    whatWeLearn: ["Kafshët e pyllit", "Foljet: vrapon, kërcen", "Ku jeton lepuri"],
    activity: "Kërce si lepuri nëpër dhomë, pastaj vizato një lepur.",
  },
  {
    id: 5,
    title: "Çoko-çoko",
    palette: "grape",
    icon: "ice-cream",
    videoUrl: "https://www.youtube.com/watch?v=1lXKr_R9Zkc",
    lyrics: [
      "Uhoopa!",
      "Të gjithë fëmijët e duan çokollatën!",
      "Oh sa e shijshme!",
      "Është e ëmbël dhe na bën të lumtur!",
      "Një, dy,",
      "Një, dy, tre, katër!",
      "Çoko-çoko!",
      "",
      "Çoko-çoko-lata",
      "Çoko-çoko-lata!",
      "Të gjithë duan çokollatë!",
      "Çoko-çoko-lata",
      "Çoko-çoko-lata!",
      "Të gjithë duan çokollatë!",
      "",
      "Çoko-çoko",
      "Çoko-çoko!",
      "Çoko-çoko",
      "Çoko-çoko!",
      "Çoko-çoko-çoko-çoko-Çokollatë!",
      "",
      "Të këndojmë prapë!",
      "",
      "Çoko-çoko-lata",
      "Çoko-çoko-lata!",
      "Të gjithë duan çokollatë!",
      "Çoko-çoko-lata!",
      "Çoko-çoko-lata!",
      "Të gjithë duan çokollatë!",
      "Çoko-çoko",
      "Çoko-çoko",
      "Çoko-çoko",
      "Çoko-çoko",
      "Çoko-çoko-çoko-çoko - Çokollatë!",
      "",
      "E dua çokollatën!",
      "Është e ëmbël dhe e shijshme!",
      "Yummy!",
    ],
    highlights: ["Çoko-çoko", "Çokollatë"],
    newWords: [
      { word: "Çokollatë", meaning: "ëmbëlsirë kafe që të gjithë e duan" },
      { word: "E ëmbël", meaning: "shije si sheqeri ose mjalti" },
      { word: "E shijshme", meaning: "që ka shije shumë të mirë" },
    ],
    whatWeLearn: ["Numërojmë 1, 2, 3, 4", "Fjalë për shijen: e ëmbël, e shijshme", "Rrokja ço-ko"],
    activity: "Vizato çokollatën tënde të preferuar.",
  },
  {
    id: 6,
    title: "Klap-klap",
    palette: "sky",
    icon: "fish",
    videoUrl: "https://www.youtube.com/watch?v=D6ccYlVkh-A",
    lyrics: [
      "Përplas duart bashkë, përplas duart",
      "Përplas duart bashkë - 1,2,3.",
      "",
      "Klap-klap këndej",
      "Klap-klap andej",
      "Klap-klap pa pushim",
      "1,2,3.",
      "x2",
      "",
      "Kur dal në breg,",
      "Shoh shumë shalqi,",
      "Prapë në shtëpi",
      "S’dua të shkoj",
      "Se nëse shkoj,",
      "Mami më thotë:",
      "A ke parë ti ndonjë dre",
      "Që lëngun ngreh?",
      "Kur del në breg",
      "",
      "Kur dal në breg,",
      "Shoh shumë shalqi,",
      "Prapë në shtëpi",
      "S’dua të shkoj",
      "Se nëse shkoj,",
      "Mami më thotë:",
      "A ke parë ti një balenë",
      "Që libra blen?",
      "Kur del në breg!",
      "",
      "Kur dal në breg,",
      "Shoh shumë shalqi,",
      "Prapë në shtëpi",
      "S’dua të shkoj",
      "Se nëse shkoj,",
      "Mami më thotë:",
      "A ke parë ti një ari",
      "Që të ndërtojë di?",
      "Kur del në breg",
      "",
      "Kur dal në breg,",
      "E shoh shumë shalqi,",
      "Prapë në shtëpi",
      "S’dua të shkoj",
      "Se nëse shkoj,",
      "Mami më thotë:",
      "A ke parë ti një ari",
      "Që të ndërtojë di?",
      "(ose nëse nuk përshtatet fjala ndërtojë, le të bëhet: që shumë gjëra di?)",
      "Kur del në breg",
      "",
      "Kur dal në breg,",
      "E shoh shumë shalqi,",
      "Prapë në shtëpi",
      "S’dua të shkoj",
      "Se nëse shkoj,",
      "Mami më thotë:",
      "A ke parë ti ndonjë mi",
      "Që rri si zotëri?",
      "Kur del në breg",
    ],
    highlights: ["Klap-klap", "Kur dal në breg"],
    newWords: [
      { word: "Duar", meaning: "pjesë e trupit me të cilat kapim" },
      { word: "Breg", meaning: "ana e detit ose e lumit" },
      { word: "Shalqi", meaning: "fruti i madh, jeshil jashtë e i kuq brenda" },
    ],
    whatWeLearn: ["Duartrokitja me ritëm 1, 2, 3", "Këndej dhe andej", "Kafshët: dre, balenë, ari, mi"],
    activity: "Duartrokit sipas ritmit: klap-klap-klap, 1, 2, 3.",
  },
  {
    id: 7,
    title: "Përgatitja e kekut",
    englishTitle: "Cupcake song",
    palette: "coral",
    icon: "paw",
    videoUrl: "https://www.youtube.com/watch?v=cCrDKltXFWw",
    lyrics: [
      "Hej, sot do të gatuajmë kek!",
      "A jeni gati për argëtim?",
      "Po!",
      "Miellin, të lutem!",
      "Rrofsh!  -(ose faleminderit, nëse përshtatet më mirë)",
      "",
      "Tani po i vendos të gjitha bashkë, me duar",
      "Ose, po e gjuaj përnjëherë!",
      "",
      "Opsss.. Çfarë gabimi!",
      "Më fal mami!",
      "S’ka problem i vogli im",
      "Kështu mësojmë!",
      "",
      "Pluhurin për pjekje, të lutem!",
      "Hmm...Interesante",
      "Rrahësen, të lutem!",
      "Rrofsh! Rrofsh!",
      "",
      "Sa mirë u përzien!",
      "Mrekulli!",
      "Sheqerin, të lutem!",
      "Faleminderit shumë!",
      "Ua, sa shumë sheqer kemi hedhur",
      "Do të bëhet shumë shumë e shijshme!",
      "Yummy!",
      "",
      "Tani, kush e ka radhën?",
      "Mmmm...",
      "Gjalpin, të lutem!",
      "Do ta përziej me duar!",
      "Po shkrihet!",
      "",
      "Lugën, të lutem!",
      "Yummy!",
      "A do ta provosh mami?",
      "Ta përfundojmë njëherë, Ben!",
      "",
      "Vezët, të lutem!",
      "Faleminderit shumë!",
      "Kremin, të lutem!",
      "Mirë, mbaruam!",
      "Tani, ta vendosim në tepsi!",
      "",
      "Për pak harruam!",
      "Do t’i bënim me çokollatë!",
      "Ooo..",
      "Tani t’i vendosim në furrë!",
      "Piqen në 170 gradë",
      "Për pesëmbëdhjetë minuta",
      "",
      "Mbaruam miq!",
      "",
      "Të lutem m’i sill kekët, të lutem!",
      "Rrofsh!",
      "",
      "Po sikur t’i dekorojmë?",
      "Dua ta dekoroj këtë, këtë - të gjithë!",
      "Mirë!",
      "M’i sill fluskat, të lutem!",
      "Oh, sa argëtim!",
      "",
      "Shumë urime për ty!",
      "Shumë urime për ty!",
      "Shumë urime, shumë urime!",
      "Shumë urime për ty!",
      "",
      "Ta fryej tani?",
    ],
    highlights: ["të lutem", "Yummy"],
    newWords: [
      { word: "Miell", meaning: "pluhur i bardhë për të bërë bukë e kek" },
      { word: "Vezë", meaning: "e rrumbullakët, na e jep pula" },
      { word: "Furrë", meaning: "ku piqen kekët dhe buka" },
    ],
    whatWeLearn: ["Fjalë të sjellshme: të lutem, faleminderit", "Përbërësit e një keku", "Radha: hap pas hapi"],
    activity: "Vizato përbërësit e kekut: miell, vezë, sheqer, gjalpë.",
  },
  {
    id: 8,
    title: "5 shokët",
    englishTitle: "Five little friends",
    palette: "tangerine",
    icon: "star",
    videoUrl: "https://www.youtube.com/watch?v=ghs0rW9FaBc",
    lyrics: [
      "Atje në thellësi të pyllit",
      "dy xhuxhë të lumtur jetojnë",
      "",
      "Edhe zogu del nga trungu,",
      "Në këtë shtëpi do të shkojë!",
      "“Hup-hup-hup",
      "Hup-hup-hup",
      "Unë me ju a mund t’jetoj?",
      "Hup-hup-hup",
      "Hup-hup-hup",
      "Unë me ju a mund t’jetoj?”",
      "",
      "Bretkosa që vjen nga lumi",
      "Sheh shtëpinë dhe bën",
      "“Ju-huu",
      "Më në fund unë ju gjeta",
      "Dua të jetoj me ju",
      "Hop-Hop-Hop",
      "Hop-Hop-Hop",
      "Dua të jetoj me ju",
      "Hop-Hop-Hop",
      "Hop-Hop-Hop",
      "Dua të jetoj me ju”",
      "",
      "Çfarë po kërcëllon nën shkure?",
      "Oh është miu lakmiqar",
      "“Që nga larg unë kam ardhur,",
      "T'i gjej dy xhuxhët bujarë",
      "Skuiki-skuik- Skuiki-skuik-",
      "N’këtë shtëpi a mund t’jetoj?",
      "Skuiki-skuik- Skuiki-skuik-",
      "N’këtë shtëpi a mund t’jetoj?”",
      "",
      "Atje në thellësi të pyllit,",
      "Pesë shokë të lumtur jetojnë",
      "Të gjithë bashkë i ndajnë punët",
      "Dhe shtëpinë nuk e dëmtojnë!",
      "La-la-la-la",
      "Në shtëpi të gjithë jetojnë",
      "La-la-la-la",
      "Në shtëpi të gjithë jetojnë!",
    ],
    highlights: ["Hup-hup-hup", "La-la-la-la"],
    newWords: [
      { word: "Pyll", meaning: "vend me shumë pemë" },
      { word: "Xhuxh", meaning: "njeri shumë i vogël nga përrallat" },
      { word: "Bretkosë", meaning: "kafshë e vogël jeshile që kërcen dhe bën kuak" },
    ],
    whatWeLearn: ["Kafshët e pyllit dhe zërat e tyre", "Të jetojmë bashkë si shokë", "Numri 5"],
    activity: "Vizato pesë shokët që jetojnë bashkë në shtëpi.",
  },
  {
    id: 9,
    title: "Nëse je i lumtur",
    palette: "apple",
    icon: "musical-notes",
    videoUrl: "https://www.youtube.com/watch?v=ChXMtdpY2iA",
    lyrics: [
      "Nëse sot je i lumtur përplas duart",
      "Nëse sot je i lumtur përplas duart",
      "Nëse i lumtur je vërtet",
      "Nga gëzimi kërce shpejt",
      "Nëse sot je i lumtur përplas duart",
      "",
      "Nëse sot je i lumtur shkelmo fort",
      "Nëse sot je i lumtur shkelmo fort",
      "Nëse i lumtur ndihesh sot",
      "Aty ulur mos rri kot",
      "Nëse sot je i lumtur shkelmo fort",
      "",
      "Nëse sot je i lumtur sillu shpejt",
      "Nëse sot je i lumtur sillu shpejt",
      "Nëse i lumtur je vërtet",
      "Lëre trupin ta thotë vetë",
      "Nëse sot je i lumtur sillu shpejt",
      "",
      "Nëse sot je i lumtur lëviz kokën",
      "Nëse sot je i lumtur lëviz kokën",
      "Nëse sot je i lumtur",
      "Preke qiellin edhe tokën",
      "Nëse sot je i lumtur lëviz kokën",
      "",
      "Nëse sot je i lumtur lëviz këmbët",
      "Nëse sot je i lumtur lëviz këmbët",
      "Nëse sot je i lumtur",
      "Buzëqesh dhe tregoj dhëmbët",
      "Nëse sot je i lumtur lëviz këmbët",
      "",
      "Nëse sot je i lumtur kërcit gishtat",
      "Nëse sot je i lumtur kërcit gishtat",
      "Nëse sot je i lumtur",
      "Luaj derisa t’ikin dritat",
      "Nëse sot je i lumtur kërcit gishtat",
      "",
      "Nëse i lumtur je vërtet",
      "Nga gëzimi kërce shpejt",
      "Nëse sot je i lumtur përplas duart",
    ],
    highlights: ["Nëse sot je i lumtur", "përplas duart"],
    newWords: [
      { word: "I lumtur", meaning: "kur ndihesh mirë dhe qesh" },
      { word: "Gëzim", meaning: "ndjenja e lumturisë" },
      { word: "Buzëqeshje", meaning: "kur hap buzët nga gëzimi" },
    ],
    whatWeLearn: ["Pjesët e trupit: duar, këmbë, kokë, gishta", "Të shprehim gëzimin", "Ndjekim udhëzime me lëvizje"],
    activity: "Trego me trup si je i lumtur: përplas duart dhe kërce.",
  },
  {
    id: 10,
    title: "Kopshti",
    englishTitle: "Mary, Mary quite contrary",
    palette: "instrument",
    icon: "flower",
    videoUrl: "https://www.youtube.com/watch?v=BhqF13TRN-E",
    lyrics: [
      "Iku hëna, doli dielli",
      "Kopshti prapë lulëzon",
      "",
      "Me shumë ngjyra",
      "Gjithë natyra",
      "Lulet nga gjumi i zgjon!",
    ],
    highlights: ["Kopshti prapë lulëzon"],
    newWords: [
      { word: "Hënë", meaning: "drita e natës në qiell" },
      { word: "Diell", meaning: "drita e ditës që na ngroh" },
      { word: "Natyrë", meaning: "lulet, pemët e kafshët rreth nesh" },
    ],
    whatWeLearn: ["Dita dhe nata: diell e hënë", "Ngjyrat në natyrë", "Si lulëzon kopshti"],
    activity: "Vizato një kopsht me shumë ngjyra.",
  },
  {
    id: 11,
    title: "Kukulla e Anës",
    englishTitle: "Miss Polly had a dolly",
    palette: "movement",
    icon: "musical-notes",
    videoUrl: "https://www.youtube.com/watch?v=S470c3GYgjc",
    lyrics: [
      "Kukulla e Anës ndihej keq-keq-keq",
      "Doktorin thirri Ana të vijë shpejt-shpejt-shpejt!",
      "",
      "Me çantë dhe me mjete ai u nis me vrap",
      "Në minutë dera e Anës bëri tak-tak-tak!",
      "",
      "Kukullën në dorë mori dhe e kontrolloi",
      "Dhe në shtrat tha vendose, duhet të pushojë.",
      "",
      "Më vonë kukulla do ndihet mire-mirë-mirë",
      "Dhe fatura për ty do të jetë e lirë-lirë-lirë!",
    ],
    highlights: ["keq-keq-keq", "tak-tak-tak"],
    newWords: [
      { word: "Kukull", meaning: "lodra si njeri i vogël" },
      { word: "Doktor", meaning: "ai që na shëron kur jemi sëmurë" },
      { word: "Sëmurë", meaning: "kur nuk ndihemi mirë" },
    ],
    whatWeLearn: ["Të kujdesemi për të tjerët", "Puna e doktorit", "Tingujt: keq-keq, tak-tak"],
    activity: "Bëhu doktor: kujdesu për kukullën ose lodrën tënde.",
  },
  {
    id: 12,
    title: "Zoti Maçok",
    englishTitle: "Mister Cat",
    palette: "nature",
    icon: "paw",
    videoUrl: "https://www.youtube.com/watch?v=5eeyWeqTuvs",
    lyrics: [
      "x2",
      "Nëpër rrugë sikur zotëri",
      "Tam-dum, ta-dum-tum-tum!",
      "Maçoku kërkon një mi",
      "Tam-dum, ta-dum-tum-tum!",
      "",
      "Dhe në plehëra ai kërkon",
      "Tam-dum, ta-dum-tum-tum",
      "Miun do që ta shijojë!",
      "",
      "Ta-da-da!",
      "",
      "Maçoku nuk ndalet",
      "Miu shumë i hahet",
      "Me veten ngushëllohet",
      "Miu do dorëzohet!",
      "",
      "Pas një viti, në këtë qoshe",
      "Tam-dum, ta-dum-tum-tum",
      "Vjen me macen çamarroke",
      "Tam-dum, ta-dum-tum-tum",
      "8 kotelet po i mësojnë",
      "Tam-dum, ta-dum-tum-tum",
      "Miun si do ta kërkojnë!",
      "",
      "Maçoku nuk ndalet",
      "Miu shumë i hahet",
      "Me veten ngushëllohet",
      "Miu do dorëzohet!",
    ],
    highlights: ["Tam-dum", "Miu do dorëzohet"],
    newWords: [
      { word: "Maçok", meaning: "mace mashkull" },
      { word: "Mi", meaning: "kafshë e vogël gri që e ndjek macja" },
      { word: "Kotele", meaning: "macet e vogla" },
    ],
    whatWeLearn: ["Macja dhe miu", "Të mos dorëzohemi", "Ritmi: tam-dum"],
    activity: "Vizato maçokun që ndjek miun.",
  },
  {
    id: 13,
    title: "Mami në market",
    englishTitle: "Mommy is walking to the market",
    palette: "grape",
    icon: "paw",
    videoUrl: "https://www.youtube.com/watch?v=cwRwscENGec",
    lyrics: [
      "Për market mami po niset",
      "Dhe macja i shkon nga pas",
      "I ndihmon të sjellë ushqimet",
      "Që të gjithë t’i hamë bashkë!",
      "",
      "Por gjatë rrugës macja ndalet",
      "Se miun e sheh nga larg",
      "Ka shumë kohë që e ka kërkuar",
      "Ndaj me të do t’luajë pak!",
      "",
      "Qeni që nga larg shikoi",
      "Përtej gardhit ai vrapoi",
      "Macën shumë e frikësoi",
      "Aq sa miun e harroi!",
      "",
      "Macja nuk zbriste nga gardhi",
      "Me qenin nuk fliste dot",
      "Po çfarë bëra unë i shkreti",
      "Doja që të luajmë tok!",
      "",
      "Ik atje ti qen i shpifur",
      "Me ty nuk dua të rri",
      "Miun nga unë e shpëtove",
      "Mos u bëj sikur s’e di!",
      "",
      "Këto fjalë me të dëgjuar",
      "Qeni u nis për shtëpi",
      "Unë dhe miu u afruam",
      "Qenit do t’i bëjmë shoqëri!",
    ],
    highlights: ["e sheh nga larg", "do t’i bëjmë shoqëri"],
    newWords: [
      { word: "Market", meaning: "dyqani ku blejmë ushqime" },
      { word: "Gardh", meaning: "rrethimi rreth shtëpisë ose kopshtit" },
      { word: "Shoqëri", meaning: "të jesh shok me dikë" },
    ],
    whatWeLearn: ["Kafshët: mace, mi, qen", "Të bëhemi shokë", "Ndihma në shtëpi"],
    activity: "Vizato macën, miun dhe qenin që bëhen shokë.",
  },
  {
    id: 14,
    title: "Te floktari",
    englishTitle: "My baby’s first haircut",
    palette: "sky",
    icon: "cut",
    videoUrl: "https://www.youtube.com/watch?v=8RZ8tGKxI0g",
    lyrics: [
      "Për herë të parë në jetë",
      "Te floktari shkova vetë!",
      "",
      "A m’i pret flokët, më fal?",
      "Nga sot unë ndihem i madh!",
      "",
      "Shokët do t’më kenë zili",
      "Të gjithë do të vijnë te ti!",
      "",
      "Ma bëj një model të mirë",
      "Dua të bëhem me stil!",
      "",
      "Unë i vogël nuk jam më",
      "Flokët e gjata nuk i lë!",
      "",
      "Unë te ti tani vi vetë",
      "Mami jashtë mua më pret!",
    ],
    highlights: ["ndihem i madh"],
    newWords: [
      { word: "Floktar", meaning: "ai që na pret flokët" },
      { word: "Flokë", meaning: "qimet mbi kokë" },
      { word: "Model", meaning: "forma si na priten flokët" },
    ],
    whatWeLearn: ["Të rritemi", "Puna e floktarit", "Të jemi të guximshëm për gjëra të reja"],
    activity: "Vizato veten me një model të ri flokësh.",
  },
  {
    id: 15,
    title: "Shoqja ime Lara",
    englishTitle: "My friend Lola",
    palette: "coral",
    icon: "paw",
    videoUrl: "https://www.youtube.com/watch?v=vCku2m77UpE",
    lyrics: [
      "Kjo është Lara,",
      "Kjo është Lara,",
      "Trupi i saj është me të zeza dhe të bardha",
      "",
      "Shoqja ime Lara,",
      "Shoqja ime Lara,",
      "Ajo nuk flet por bën mu-uu!",
      "Ajo bën mu-uu,",
      "Mu-uu-uu",
    ],
    highlights: ["mu-uu", "Shoqja ime Lara"],
    newWords: [
      { word: "Lopë", meaning: "kafshë e madhe që na jep qumësht" },
      { word: "E bardhë dhe e zezë", meaning: "ngjyrat e Larës" },
      { word: "Mu", meaning: "zëri që bën lopa" },
    ],
    whatWeLearn: ["Ngjyrat: e bardhë dhe e zezë", "Zëri i lopës: mu", "Kafshët e fermës"],
    activity: "Ngjyros lopën Lara me njolla të bardha e të zeza.",
  },
  {
    id: 16,
    title: "Zigalu",
    englishTitle: "Zigaloo Dance",
    palette: "tangerine",
    icon: "paw",
    videoUrl: "https://www.youtube.com/watch?v=ovdjNo0p97A",
    lyrics: [
      "Oh, Oh-oh-oh-oh-oh",
      "Oh-oh-oh-oh-oh",
      "Oh-oh-oh-oh-oh,",
      "Zigalu, Zigalu",
      "",
      "Kam një shok të vogël",
      "Do luaj me ju",
      "Është një dino i lezetshëm",
      "Emri i tij është Zigalu!",
      "",
      "Uh, uh-uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh,",
      "Zigalu, Zigalu",
      "",
      "Ai lëviz këmbën",
      "Ti qoje dorën",
      "Dridhu pak",
      "Vazhdoje lojën!",
      "",
      "Uh, uh-uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh,",
      "Zigalu, Zigalu",
      "",
      "Ti lëviz këmbën",
      "Ai çon dorën",
      "Dridhu pak",
      "Fitoje lojën!",
      "",
      "Uh, uh-uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh,",
      "Zigalu, Zigalu",
      "",
      "Një hap përpara",
      "Një kërcim majtas",
      "Kapja dorën",
      "Kthehu djathtas!",
      "",
      "Uh, uh-uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh,",
      "Zigalu, Zigalu",
      "",
      "Tani dridhet",
      "Bishtin po e tund",
      "Kokën po e kruan",
      "Si një majmun!",
      "",
      "Uh, uh-uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh,",
      "Zigalu, Zigalu",
      "",
      "Ec si pinguin",
      "Shëtite gjithë botën",
      "Mos u ndal",
      "Fitoje lojën!",
      "",
      "Uh, uh-uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh,",
      "Zigalu, Zigalu",
      "",
      "Tani erdhi",
      "Pjesa më e mirë",
      "Si një astronaut",
      "Shko në hapësirë! (hap’sirë)",
      "",
      "Uh, uh-uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh,",
      "Zigalu, Zigalu",
      "",
      "Rri në gishta",
      "Sikur një gjirafë",
      "Përkulu poshtë",
      "Si bretkosë!",
      "",
      "Uh, uh-uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh",
      "Uh, uh-uh-uh-uh,",
      "Zigalu, Zigalu",
    ],
    highlights: ["Zigalu, Zigalu", "Uh, uh-uh-uh"],
    newWords: [
      { word: "Dino", meaning: "dinozaur, kafshë e madhe nga kohët e vjetra" },
      { word: "Pinguin", meaning: "zog i zi e bardhë që ecën ngadalë" },
      { word: "Gjirafë", meaning: "kafshë me qafë shumë të gjatë" },
    ],
    whatWeLearn: ["Pjesët e trupit dhe lëvizjet", "Majtas – djathtas, përpara", "Imitojmë kafshët"],
    activity: "Vallëzo si Zigalu: lëviz këmbën, dorën dhe dridhu pak!",
  },
  {
    id: 17,
    title: "Pinjata",
    englishTitle: "Break the Pinata",
    palette: "apple",
    icon: "balloon",
    videoUrl: "https://www.youtube.com/watch?v=z-04mKmxFNw",
    lyrics: [
      "Pinjata",
      "3,2,1,",
      "Befasi",
      "",
      "Pinjata është befasia më e mirë për çdo festë!",
      "",
      "Të luajmë e të këndojmë",
      "Festa po fillon!",
      "",
      "Kush do ta gjuajë pinjatën?",
      "Jo",
      "A do ta gjuajë ai pinjatën?",
      "Jo",
      "A do ta gjuajë ajo pinjatën?",
      "Jo",
      "A do ta gjuajë ai pinjatën?",
      "Jo",
      "Koha ta gjuajmë pinjatën!",
      "",
      "O mami, o mami",
      "Me ndihmo të lutem",
      "Po theva pinjatën",
      "Do bëhem fitues!",
      "O mami, o mami",
      "Sytë a m’i mbulon ti?",
      "Kur thehet pinjata",
      "Na del një befasi!",
      "",
      "Sillu sillu",
      "Sillu rreth pinjatës",
      "Gjuaj gjuaj",
      "Gjuaje pinjatën x3",
      "",
      "Kush do ta gjuajë pinjatën?",
      "Jo",
      "A do ta gjuajë ai pinjatën?",
      "Jo",
      "A do ta gjuajë ajo pinjatën?",
      "Jo",
      "A do ta gjuajë ai pinjatën?",
      "Jo",
      "Koha ta gjuajë pinjatën!",
      "",
      "O mami, o mami",
      "Me ndihmo të lutem",
      "Po theva pinjatën",
      "Do bëhem fitues!",
      "O mami, o mami",
      "Sytë a m’i mbulon ti?",
      "Kur thehet pinjata",
      "Na del një befasi!",
      "",
      "Sillu sillu",
      "Sillu rreth pinjatës",
      "Gjuaj gjuaj",
      "Gjuaje pinjatën x3",
    ],
    highlights: ["Sillu sillu", "Gjuaje pinjatën"],
    newWords: [
      { word: "Pinjatë", meaning: "lodër me ëmbëlsira brenda që e thyejmë në festë" },
      { word: "Befasi", meaning: "diçka që nuk e prisje" },
      { word: "Festë", meaning: "ditë gëzimi me shokë" },
    ],
    whatWeLearn: ["Ai dhe ajo: djali dhe vajza", "Numërojmë 3, 2, 1", "Radha kur luajmë"],
    activity: "Vizato pinjatën tënde dhe çfarë do të dilte nga brenda.",
  },
  {
    id: 18,
    title: "Çu-Çu-Ua",
    englishTitle: "Choo Coo WAH",
    palette: "instrument",
    icon: "musical-notes",
    image: require("@/assets/images/song-dance.jpg"),
    videoUrl: "https://www.youtube.com/watch?v=RWt5XtOMT2I",
    lyrics: [
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua – Ua",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua - Ua",
      "",
      "Gatitu!",
      "Duart drejt!",
      "Gatitu!",
      "Duart drejt!",
      "",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua – Ua",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua - Ua",
      "",
      "Gatitu",
      "Duart drejt",
      "Mbildhe grushtin",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua – Ua",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua - Ua",
      "",
      "Gatitu",
      "Duart drejt",
      "Mbildhe grushtin",
      "Gishti lart",
      "",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua – Ua",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua - Ua",
      "",
      "Vëmendje",
      "Si urdhëro",
      "",
      "1,2,3,4",
      "Marsho",
      "",
      "Gatitu",
      "Duart drejt",
      "Mbildhe grushtin",
      "Gishti lart",
      "Mbildhi krahët",
      "",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua – Ua",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua - Ua",
      "",
      "Gatitu",
      "Duart drejt",
      "Mbildhe grushtin",
      "Gishti lart",
      "Mbildhi krahët",
      "Lëviz kokën",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua - Ua",
      "",
      "Gatitu",
      "Duart drejt",
      "Mbildhe grushtin",
      "Gishti lart",
      "Mbildhi krahët",
      "Lëviz kokën",
      "Të pasmet jashtë!",
      "",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua - Ua",
      "",
      "Gatitu",
      "Duart drejt",
      "Mbildhe grushtin",
      "Gishti lart",
      "Mbildhi krahët",
      "Lëviz kokën",
      "Të pasmet jashtë!",
      "Si një pinguin",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua – Ua x2",
      "",
      "Gatitu",
      "Duart drejt",
      "Mbildhe grushtin",
      "Gishti lart",
      "Mbildhi krahët",
      "Lëviz kokën",
      "Të pasmet jashtë!",
      "Si një pinguin",
      "Nxirr gjuhën!",
      "Çu-Çu-Ua Çu-Çu-Ua Çu-Çu-Ua – Ua – Ua",
    ],
    highlights: ["Çu-Çu-Ua", "Marsho"],
    newWords: [
      { word: "Grusht", meaning: "dora e mbyllur fort" },
      { word: "Marsho", meaning: "ec me ritëm si ushtar" },
      { word: "Pinguin", meaning: "zog i zi e bardhë që ecën ngadalë" },
    ],
    whatWeLearn: ["Ndjekim urdhra me lëvizje", "Numërojmë 1, 2, 3, 4", "Pjesët e trupit"],
    activity: "Bëj lëvizjet e këngës: duart drejt, gishti lart, marsho!",
  },
  {
    id: 19,
    title: "Dyqani muzikor",
    englishTitle: "Musical Instruments Song",
    palette: "movement",
    icon: "musical-notes",
    image: require("@/assets/images/song-instruments.jpg"),
    videoUrl: "https://www.youtube.com/watch?v=mgw_lKi1JuI",
    lyrics: [
      "Në dyqanin muzikor",
      "Bleva një flautë, një flautë",
      "Tu-lu-hu-lu-u një flautë!",
      "",
      "Sha-la-la",
      "Sha-la-li",
      "Muzika më jep lumturi!",
      "",
      "Sha-la-la",
      "Sha-la-li",
      "Të luaj vegla unë di!",
      "",
      "Në dyqanin muzikor",
      "Bleva një piano, një piano",
      "Plink-plink-plink një piano",
      "Tu-lu-hu-lu-u një flautë!",
      "",
      "Sha-la-la",
      "Sha-la-li",
      "Muzika më jep lumturi!",
      "",
      "Sha-la-la",
      "Sha-la-li",
      "Të luaj vegla unë di!",
      "",
      "Në dyqanin muzikor",
      "Bleva një trumpetë, një trumpetë",
      "Prum-tum-tum, një trumpetë",
      "Plink-plink-plink një piano",
      "Tu-lu-hu-lu-u një flautë!",
      "",
      "Sha-la-la",
      "Sha-la-li",
      "Muzika më jep lumturi!",
      "",
      "Sha-la-la",
      "Sha-la-li",
      "Të luaj vegla unë di!",
      "",
      "Në dyqanin muzikor",
      "Bleva violinçel, një violinçel",
      "zum-zum-zum një violinçel",
      "Prum-tum-tum, një trumpetë",
      "Plink-plink-plink një piano",
      "Tu-lu-hu-lu-u një flautë!",
      "",
      "Sha-la-la",
      "Sha-la-li",
      "Muzika më jep lumturi!",
      "",
      "Sha-la-la",
      "Sha-la-li",
      "Të luaj vegla unë di!",
      "",
      "Në dyqain muzikor",
      "Bleva harmonikë, një harmonikë",
      "Ua-ui-ua, një harmonikë",
      "zum-zum-zum një violinçel",
      "Prum-tum-tum, një trumpetë",
      "Plink-plink-plink një piano",
      "Tu-lu-hu-lu-u një flautë!",
      "",
      "Sha-la-la",
      "Sha-la-li",
      "Muzika më jep lumturi!",
      "",
      "Sha-la-la",
      "Sha-la-li",
      "Të luaj vegla unë di!",
    ],
    highlights: ["Sha-la-la", "Muzika më jep lumturi"],
    newWords: [
      { word: "Flaut", meaning: "vegël frymore që e fryjmë" },
      { word: "Piano", meaning: "vegël me tasta që bën plink" },
      { word: "Trumpetë", meaning: "vegël frymore që bën prum-tum" },
    ],
    whatWeLearn: ["Veglat muzikore dhe tingujt e tyre", "Muzika na jep gëzim", "Përsëritje e tingujve"],
    activity: "Lidhe secilën vegël me tingullin që bën.",
  },
  {
    id: 20,
    title: "Shtëpia prej letre",
    englishTitle: "My Little Neighbor",
    palette: "nature",
    icon: "home",
    videoUrl: "https://www.youtube.com/watch?v=W1OEXELmkok",
    lyrics: [
      "Tungjatjeta, miku im",
      "Mirë se vjen në shtëpinë time!",
      "",
      "A e di si është e vërteta?",
      "Kjo shtëpi është bërë nga letra!",
      "Kjo shtëpi është bërë nga letra!",
      "3x",
      "",
      "Tungjatjeta - tha postieri",
      "Letra të reja kam sjell sot",
      "Për shtëpi ai u nis drejt",
      "Por nga shkallët ra në tokë",
      "Por nga shkallët ra në tokë!",
      "",
      "Dhe kështu, shtëpia ime",
      "Çdo ditë rrëzohet dhe ndërtohet",
      "Unë shokët aty i ftoj",
      "Me shtëpinë time i njoftoj!",
      "Me shtëpinë time i njoftoj!",
    ],
    highlights: ["Kjo shtëpi është bërë nga letra"],
    newWords: [
      { word: "Letër", meaning: "ajo mbi të cilën vizatojmë e shkruajmë" },
      { word: "Shtëpi", meaning: "vendi ku jetojmë" },
      { word: "Postier", meaning: "ai që sjell letrat" },
    ],
    whatWeLearn: ["Përshëndetjet: tungjatjeta, mirë se vjen", "Puna e postierit", "Të ftojmë shokët"],
    activity: "Ndërto një shtëpi të vogël me letër.",
  },
  {
    id: 21,
    title: "Vallëzimi i detarit",
    englishTitle: "The little sailor dance",
    palette: "grape",
    icon: "fish",
    videoUrl: "https://www.youtube.com/watch?v=gVT_riVua4w",
    lyrics: [
      "Vallëzimi i detarit",
      "Mes detit e larg zallit",
      "",
      "Me trup ai po vallëzon",
      "Edhe gishtin lart e çon",
      "Me gisht, gisht, gisht",
      "Është detari që vallëzon!",
      "",
      "Vallëzimi i detarit",
      "Mes detit e larg zallit",
      "",
      "Me trup ai po vallëzon",
      "Edhe dorën lart e çon",
      "Me dorë, dorë, dorë",
      "Me gisht, gisht, gisht",
      "Është detari që vallëzon!",
      "",
      "Vallëzimi i detarit",
      "Mes detit e larg zallit",
      "",
      "Me trup ai po vallëzon",
      "Edhe bërrylin lart e çon",
      "Me bërryl, bërryl, berryl",
      "Me dorë, dorë, dorë",
      "Me gisht, gisht, gisht",
      "",
      "Është detari që vallëzon!",
      "",
      "Vallëzimi i detarit",
      "Mes detit e larg zallit",
      "",
      "Me trup ai po vallëzon",
      "Edhe krahët lart i çon",
      "Me krah, krah, krah",
      "Me bërryl, bërryl, berryl",
      "Me dorë, dorë, dorë",
      "Me gisht, gisht, gisht",
      "",
      "Është detari që vallëzon!",
      "Vallëzimi i detarit",
      "Mes detit e larg zallit",
      "",
      "Me trup ai po vallëzon",
      "Edhe kokën lart e çon",
      "Me kokë, kokë, kokë",
      "Me krah, krah, krah",
      "Me bërryl, bërryl, berryl",
      "Me dorë, dorë, dorë",
      "Me gisht, gisht, gisht",
      "",
      "Është detari që vallëzon!",
      "",
      "Vallëzimi i detarit",
      "Mes detit e larg zallit",
      "",
      "Me trup ai po vallëzon",
      "Edhe bishtin lart e çon",
      "Me bisht, bisht, bisht",
      "Me kokë, kokë, kokë",
      "Me krah, krah, krah",
      "Me bërryl, bërryl, berryl",
      "Me dorë, dorë, dorë",
      "Me gisht, gisht, gisht",
      "",
      "Është detari që vallëzon!",
      "",
      "Vallëzimi i detarit",
      "Mes detit e larg zallit",
      "",
      "Me trup ai po vallëzon",
      "Edhe gjunjët lart i çon",
      "Me gjunjë, gjunjë, gjunjë",
      "Me bisht, bisht, bisht",
      "Me kokë, kokë, kokë",
      "Me krah, krah, krah",
      "Me bërryl, bërryl, bërryl",
      "Me dorë, dorë, dorë",
      "Me gisht, gisht, gisht",
      "",
      "Është detari që vallëzon!",
      "",
      "Vallëzimi i detarit",
      "Mes detit e larg zallit",
      "",
      "Me trup ai po vallëzon",
      "Edhe shputat lart i çon",
      "Me shputa, shputa, shputa",
      "Me gjunjë, gjunjë, gjunjë",
      "Me bisht, bisht, bisht",
      "Me kokë, kokë, kokë",
      "Me krah, krah, krah",
      "Me bërryl, bërryl, bërryl",
      "Me dorë, dorë, dorë",
      "Me gisht, gisht, gisht",
      "",
      "Është detari që vallëzon!",
    ],
    highlights: ["Është detari që vallëzon", "gisht, gisht, gisht"],
    newWords: [
      { word: "Detar", meaning: "ai që punon në det" },
      { word: "Bërryl", meaning: "pjesa ku përkulet krahu" },
      { word: "Gjunjë", meaning: "pjesa ku përkulet këmba" },
    ],
    whatWeLearn: ["Pjesët e trupit: gisht, dorë, bërryl, krah, kokë", "Rendi dhe përsëritja", "Vallëzim me trup"],
    activity: "Ngri lart çdo pjesë të trupit që përmend kënga.",
  },
  {
    id: 22,
    title: "Mollët dhe bananet",
    englishTitle: "Apples and Bananas",
    palette: "sky",
    icon: "musical-notes",
    image: require("@/assets/images/song-fruits.jpg"),
    videoUrl: "https://www.youtube.com/watch?v=wfrSXppk1x8",
    lyrics: [
      "A e njihni këtë këngë?",
      "",
      "Dua të ha, ha, ha molla dhe banane",
      "Dua të ha, ha, ha molla dhe banane",
      "X2",
      "",
      "Ta bëjmë qesharake?",
      "",
      "Ta kthejmë zanoren a në aj",
      "Dua të haj, haj, haj mollaj dhe bajnajne",
      "Dua të haj, haj, haj mollaj dhe bajnajne",
      "x2",
      "",
      "Ta kthejmë zanoren a në e",
      "",
      "Dua të he, he, he molle dhe benene",
      "Dua të he, he, he molle dhe benene",
      "X2",
      "",
      "Ta kthejmë zanoren a në i",
      "",
      "Dua të hi, hi, hi molli dhe binine",
      "Dua të hi, hi, hi molli dhe binine",
      "x2",
      "",
      "Ta kthejmë zanoren a në i",
      "",
      "Dua të hi, hi, hi molli dhe binine",
      "Dua të hi, hi, hi molli dhe binine",
      "X2",
      "",
      "Ta kthejmë zanoren a në o",
      "",
      "Dua të ho, ho, ho mollo dhe bonone",
      "Dua të ho, ho, ho mollo dhe bonone",
      "X2",
      "",
      "Ju lumtë!",
      "",
      "Tani kthejeni zanoren a në u",
      "",
      "Dua të hu, hu, hu mollu dhe bunune",
      "Dua të hu, hu, hu mollu dhe bunune",
      "X2",
    ],
    highlights: ["ha, ha, ha", "he, he, he"],
    newWords: [
      { word: "Zanore", meaning: "tingujt A, E, I, O, U" },
      { word: "Mollë", meaning: "fruti i kuq ose jeshil" },
      { word: "Banane", meaning: "fruti i verdhë i gjatë" },
    ],
    whatWeLearn: ["Zanoret A, E, I, O, U", "Shqiptimi i qartë", "Lojë me tingujt"],
    activity: "Këndoje këngën duke ndërruar zanoren: ha, he, hi, ho, hu!",
  },
  {
    id: 23,
    title: "Koha e Drekës",
    englishTitle: "Polly put the kettle on",
    palette: "coral",
    icon: "restaurant",
    videoUrl: "https://www.youtube.com/watch?v=I-nq0hRh4kM",
    lyrics: [
      "Ana do të bëjë çaj",
      "Çajnikun ajo vë në zjarr",
      "Sapo avulli të dalë",
      "Çajniku ndal!",
      "",
      "Lura drekën po e shtron",
      "Tavolinën zbukuron",
      "Të gjithëve po na fton",
      "Në drekë të shkojmë!",
      "",
      "Rozi pjatat po servon",
      "Lurës ajo i ndihmon",
      "Dreka gati po afron",
      "Oh sa shijon!",
      "",
      "Anash lugë dhe pirunë",
      "Për ushqim na duhen shumë",
      "Edhe thika muk mungon",
      "Dreka fillon!",
      "",
      "Gjyshi gotat po i merr",
      "Ujë dhe lëng ai do na sjellë",
      "Pas kësaj dreke të mirë",
      "Do kemi ëmbëlsirë!",
      "",
      "Mami tortën ka gatuar",
      "Sa shumë e kemi shijuar!",
      "Tani të gjithë të ndihmojmë",
      "Tavolinën ta pastrojmë!",
    ],
    highlights: ["Dreka fillon", "Oh sa shijon"],
    newWords: [
      { word: "Drekë", meaning: "ushqimi i mesditës" },
      { word: "Pirun", meaning: "me të cilin marrim ushqimin" },
      { word: "Çajnik", meaning: "ku ziejmë ujin për çaj" },
    ],
    whatWeLearn: ["Të shtrojmë tavolinën: lugë, pirun, thikë", "Ndihma në familje", "Radha e vakteve"],
    activity: "Vizato tavolinën me pjata, lugë, pirun dhe thikë.",
  },
  {
    id: 24,
    title: "Kënga e lumturisë",
    englishTitle: "Johny's Secret Song of Happiness",
    palette: "tangerine",
    icon: "happy",
    videoUrl: "https://www.youtube.com/watch?v=AvnlwY45uE4",
    lyrics: [
      "Kur të jesh keq, kur të jesh mirë",
      "Dëgjoje këngën e lumturisë!",
      "",
      "Mos ngurro",
      "Me të vallëzo",
      "Kjo është kënga e lumturisë!",
      "",
      "Du-du-da-da Du-du-du-du-du-du-du",
      "Du-du-du, Du-da-da x2",
      "Kjo është kënga e lumturisë!",
      "",
      "Mos u mërzit",
      "Buzëqeshje dhuro",
      "Me trupin tënd botën ndrysho",
      "Sa më shumë qesh",
      "Më i lumtur do jesh",
      "Me këtë këngë ti vallëzo!",
      "",
      "Du-du-da-da Du-du-du-du-du-du-du",
      "Du-du-du, Du-da-da x2",
      "",
      "Kjo është kënga e lumturisë!",
      "",
      "Du-da-da",
      "",
      "Kur të jesh keq, kur të jesh mirë",
      "Dëgjoje këngën e lumturisë!",
      "",
      "Mos ngurro",
      "Me të vallëzo",
      "Kjo është kënga e lumturisë!",
      "",
      "Du-du-da-da",
      "",
      "Mos u mërzit",
      "Buzëqeshje dhuro",
      "Me trupin tënd botën ndrysho",
      "Sa më shumë qesh",
      "Më i lumtur do jesh",
      "Me këtë këngë ti vallëzo",
      "",
      "Du-du-da-da Du-du-du-du-du-du-du",
      "Du-du-du, Du-da-da",
      "",
      "Kur të jesh keq, kur të jesh mirë",
      "Dëgjoje këngën e lumturisë!",
      "",
      "Mos ngurro",
      "Me të vallëzo",
      "Kjo është kënga e lumturisë!",
      "",
      "Du-du-da-da",
      "",
      "Mos u mërzit",
      "Buzëqeshje dhuro",
      "Me trupin tënd botën ndrysho",
      "Sa më shumë qesh",
      "Më i lumtur do jesh",
      "Me këtë këngë ti vallëzo",
      "",
      "Du-du-da-daaa",
    ],
    highlights: ["Kjo është kënga e lumturisë", "Du-du-da-da"],
    newWords: [
      { word: "Lumturi", meaning: "ndjenja kur je shumë i gëzuar" },
      { word: "Buzëqeshje", meaning: "kur qeshim me buzë" },
      { word: "Vallëzim", meaning: "të kërcesh me muzikë" },
    ],
    whatWeLearn: ["Të shprehim ndjenjat", "Buzëqeshja na bën më të lumtur", "Vallëzim me ritëm"],
    activity: "Vizato një fytyrë të lumtur që buzëqesh.",
  },
  {
    id: 25,
    title: "Ylli I vogël",
    englishTitle: "Twinkle Twinkle Little Star",
    palette: "apple",
    icon: "star",
    videoUrl: "https://www.youtube.com/watch?v=9qb-NWDBhrw",
    lyrics: [
      "Ylli i vogël lart në qiell",
      "Duket porsi zjarr në pyll",
      "Sipër dheut lart qëndron",
      "Xixa-xixa xixëllon!",
      "X2",
      "",
      "Disku i diellit kur perëndon",
      "Nata hijen e lëshon",
      "Ylli veten e zbulon",
      "Xixa-xixa xixëllon!",
      "",
      "Ylli i vogël lart në qiell",
      "Duket porsi zjarr në pyll!",
    ],
    highlights: ["Xixa-xixa xixëllon", "Ylli i vogël lart në qiell"],
    newWords: [
      { word: "Yll", meaning: "drita e vogël në qiellin e natës" },
      { word: "Qiell", meaning: "hapësira lart mbi ne" },
      { word: "Xixëllon", meaning: "shkëlqen si dritë e vogël" },
    ],
    whatWeLearn: ["Qielli natën: yje e hënë", "Dita dhe nata", "Fjalë: shkëlqen, xixëllon"],
    activity: "Vizato qiellin e natës me yje dhe hënë.",
  },
  {
    id: 26,
    title: "Sillu, Sillu",
    englishTitle: "Rolling Rolling",
    palette: "instrument",
    icon: "body",
    videoUrl: "https://www.youtube.com/watch?v=UE47niyjCOU",
    lyrics: [
      "Sillu, sillu",
      "Sillu, sillu",
      "Lart, lart, lart",
      "Sillu, sillu",
      "Sillu, sillu",
      "Poshtë, poshtë, poshtë!",
      "",
      "Shumë mirë!",
      "",
      "Sillu, sillu",
      "Sillu, sillu",
      "Lart, lart, lart",
      "Sillu, sillu",
      "Sillu, sillu",
      "Poshtë, poshtë, poshtë!",
      "",
      "Të lumtë!",
      "",
      "Sillu, sillu",
      "Sillu, sillu",
      "Djathtas, djathtas, djathtas",
      "Sillu, sillu",
      "Sillu, sillu",
      "Majtas, majtas, majtas",
      "",
      "Bëje prapë!",
      "",
      "Sillu, sillu",
      "Sillu, sillu",
      "Djathtas, djathtas, djathtas",
      "Sillu, sillu",
      "Sillu, sillu",
      "Majtas, majtas, majtas",
      "",
      "Të lumtë!",
      "",
      "Sillu, sillu",
      "Sillu, sillu",
      "Brenda, brenda, brenda",
      "Sillu, sillu Sillu, sillu",
      "Jashtë, jashtë, jashtë",
      "",
      "Edhe një herë!",
      "",
      "Sillu, sillu",
      "Sillu, sillu",
      "Brenda, brenda, brenda",
      "Sillu, sillu Sillu, sillu",
      "Jashtë, jashtë, jashtë!",
    ],
    highlights: ["Sillu, sillu"],
    newWords: [
      { word: "Lart", meaning: "drejt qiellit, nga sipër" },
      { word: "Poshtë", meaning: "drejt tokës, nga poshtë" },
      { word: "Sillu", meaning: "rrotullohu" },
    ],
    whatWeLearn: ["Lart – poshtë", "Djathtas – majtas", "Brenda – jashtë"],
    activity: "Rrotullo duart lart, poshtë, djathtas dhe majtas.",
  },
  {
    id: 27,
    title: "Njerëzit e dashur",
    englishTitle: "The more we get together",
    palette: "movement",
    icon: "heart",
    videoUrl: "https://www.youtube.com/watch?v=Yky_m1wpDIw",
    lyrics: [
      "Njerëzve të dashur, të dashur, të dashur,",
      "Njerëzve të dashur, t’u dhurojmë dashuri! x2",
      "Se çka është e imja, është dhe e jotja",
      "Kur ndajmë të mirat, më e bukur bëhet bota!",
      "",
      "Njerëzve të dashur, të dashur, të dashur,",
      "Njerëzve të dashur, t’u dhurojmë dashuri! x2",
      "",
      "Kështu bën Bingo dhe Ana dhe Beni",
      "Njerëzve të dashur, t’u dhurojmë dashuri!",
      "",
      "Njerëzve të dashur, të dashur, të dashur,",
      "Njerëzve të dashur, t’u dhurojmë dashuri! x2",
      "",
      "Se çka është e imja, është dhe e jotja",
      "Kur ndajmë të mirat, më e bukur bëhet bota!",
      "",
      "Njerëzit e dashur, na dhurojnë lumturi!",
    ],
    highlights: ["t’u dhurojmë dashuri", "të dashur, të dashur"],
    newWords: [
      { word: "Dashuri", meaning: "ndjenja e ngrohtë për të tjerët" },
      { word: "Ndaj", meaning: "jap edhe dikujt tjetër" },
      { word: "Shok", meaning: "ai me të cilin luajmë e ndajmë" },
    ],
    whatWeLearn: ["Të ndajmë me të tjerët", "Dashuria dhe miqësia", "E imja – e jotja"],
    activity: "Vizato veten duke ndarë diçka me një shok.",
  },
  {
    id: 28,
    title: "Kush është këtu?",
    englishTitle: "Peek-a-Boo",
    palette: "nature",
    icon: "musical-notes",
    videoUrl: "https://www.youtube.com/watch?v=6Hl3uE8i4CU",
    lyrics: [
      "Peek-a-Boo",
      "Peek-a-Boo",
      "Kush është këtu?",
      "Kush është këtu?",
      "",
      "Të dua",
      "Të dua",
      "Të dua",
    ],
    highlights: ["Kush është këtu?", "Të dua"],
    newWords: [
      { word: "Kush", meaning: "e pyesim për një person" },
      { word: "Këtu", meaning: "në këtë vend" },
      { word: "Të dua", meaning: "të dëshiroj shumë mirë" },
    ],
    whatWeLearn: ["Loja fshihu-duku", "Pyetja: kush është?", "Të shprehim dashurinë"],
    activity: "Luaj “kukú” me mamin: fshihu dhe dil – kush është këtu?",
  },
  {
    id: 29,
    title: "Vajza nga mali",
    englishTitle: "She’ll be coming round the mountain",
    palette: "grape",
    icon: "heart",
    videoUrl: "https://www.youtube.com/watch?v=PTIkOo5vYy0",
    lyrics: [
      "Lart nga mali po vjen vajza në shtëpi (toot, toot)",
      "Lart nga mali po vjen vajza në shtëpi",
      "Lart nga mali ku ka lozur në natyrën e përsosur",
      "Lart nga mali po vjen vajza në shtëpi",
      "",
      "Si në përralla do të hipë ajo mbi kalë (yee haw!)",
      "Si në përralla do të hipë ajo mbi kalë",
      "Si në përralla rruga i hapet kur në breg ajo të shfaqet",
      "Si në përralla do të hipë ajo mbi kalë",
      "",
      "Të gjithë bashkë ne do ta presim me gëzim (hi babe)",
      "Të gjithë bashkë ne do ta presim me gëzim",
      "Të gjithë bashkë ne do këndojmë zemrën e saj do ta fitojmë",
      "Të gjithë bashkë ne do ta presim me gëzim",
      "",
      "N’mesin tonë ajo ka ardhur jupi-jeej",
      "N’mesin tonë ajo ka ardhur jupi-jeej",
      "N’mesin tonë ajo ka ardhur zemrat tona i kemi hapur",
      "N’mesin tonë ajo ka ardhur jupi-jeej",
      "",
      "N’mesin tonë ajo ka ardhur zemrat tona i kemi hapur",
      "N’mesin tonë ajo ka ardhur jupi-jeej",
    ],
    highlights: ["Lart nga mali po vjen vajza", "toot, toot"],
    newWords: [
      { word: "Mal", meaning: "vend shumë i lartë me pemë e gurë" },
      { word: "Kalë", meaning: "kafshë e madhe që e kalërojmë" },
      { word: "Natyrë", meaning: "pyjet, malet e lumenjtë" },
    ],
    whatWeLearn: ["Mali dhe natyra", "Të mirëpresim dikë me gëzim", "Kafshët: kali"],
    activity: "Vizato malin dhe vajzën që vjen mbi kalë.",
  },
  {
    id: 30,
    title: "Arushi në mal",
    englishTitle: "The bear went over the mountain",
    palette: "sky",
    icon: "paw",
    image: require("@/assets/images/song-bear.jpg"),
    videoUrl: "https://www.youtube.com/watch?v=5UKMuidiUVQ",
    lyrics: [
      "Në mal arushi po ngjitet",
      "Në mal arushi po ngjitet",
      "Në mal arushi po ngjitet",
      "Të shohë çfarë mund të ketë x3",
      "",
      "Por përveç pemëve t’blerta",
      "Por përveç pemëve t’blerta",
      "Por përveç pemëve t’blerta",
      "Asgjë tjetër nuk u gjet!",
      "",
      "Më pas ai shkoi te lumi",
      "Më pas ai shkoi te lumi",
      "Më pas ai shkoi të lumi",
      "Të shohë çfarë mund të ketë x3",
      "",
      "Por përveç ujit të kaltër",
      "Por përveç ujit të kaltër",
      "Por përveç ujit të kaltër",
      "Asgjë tjetër nuk u gjet!",
      "",
      "Në livadh më pas shkoi",
      "Në livadh më pas shkoi",
      "Në livadh më pas shkoi",
      "Të shohë çfarë mund të ketë x3",
      "",
      "Atje Larën takoi",
      "Atje Larën takoi",
      "Atje Larën takoi",
      "Dhe një lule i dhuroi",
      "",
      "Një arush tjetër e gjeti",
      "Një arush tjetër e gjeti",
      "Një arush tjetër e gjeti",
      "Me gëzim e pëqafoi x3",
      "",
      "Të dy ishin të lumtur",
      "Të dy ishin të lumtur",
      "Të dy ishin të lumtur",
      "Tani loja do fillojë!",
    ],
    highlights: ["Të shohë çfarë mund të ketë", "Asgjë tjetër nuk u gjet"],
    newWords: [
      { word: "Mal", meaning: "vend i lartë me pemë" },
      { word: "Livadh", meaning: "fushë me bar të gjelbër" },
      { word: "Arush", meaning: "ariu i vogël" },
    ],
    whatWeLearn: ["Natyra: mal, lumë, livadh", "Ngjyrat: pemë të blerta, ujë i kaltër", "Përsëritje ritmike"],
    activity: "Vizato malin, lumin dhe livadhin ku shkoi arushi.",
  },
  {
    id: 31,
    title: "Miushi doli nga një vrimë",
    palette: "coral",
    icon: "paw",
    videoUrl: "https://www.youtube.com/watch?v=mlz704rvnso",
    lyrics: [
      "Aty kishte bërë shtëpinë",
      "Macja e pa mjau-mjau-mjau",
      "Pas tij vrapit nuk ia ndau!",
      "",
      "Aty kishte bërë shtëpinë",
      "Qenin thirri ham-ham-ham",
      "Më ndihmo se shok të kam!",
      "",
      "Aty kishte bërë shtëpinë",
      "Naten djathin kishte vjedhur",
      "Kur macja ishte duke fjetur!",
      "",
      "x2",
    ],
    highlights: ["mjau-mjau-mjau", "ham-ham-ham"],
    newWords: [
      { word: "Miush", meaning: "miu i vogël" },
      { word: "Vrimë", meaning: "vend i vogël i hapur ku futet miu" },
      { word: "Djathë", meaning: "ushqim i verdhë nga qumështi" },
    ],
    whatWeLearn: ["Kafshët dhe zërat: mjau, ham", "Macja, qeni dhe miu", "Tingujt e kafshëve"],
    activity: "Vizato miushin që del nga vrima.",
  },
  {
    id: 32,
    title: "Zilja tring",
    palette: "tangerine",
    icon: "heart",
    videoUrl: "https://www.youtube.com/watch?v=WE-tuKjokp0",
    lyrics: [
      "Zilja tring, zilja tring, zilja tringëllon",
      "O sa bukur qeshim ne zemrat na i gëzon, hej!",
      "Shkon kjo saja shkon, me gjithë atë shpejtësi,",
      "Mbi dëborë shkel, sikur fluturon!",
      "Me gaz e hare, zemrat na i gëzon",
      "Zilet fort kumbojnë,",
      "Tringëllimat lart jehojnë, hej!",
      "Zilja tring, zilja tring, zilja tringëllon",
      "O sa bukur qeshim ne zemrat na i gëzon, hej!",
      "O sa bukur qeshim ne zemrat na i gëzon...",
    ],
    highlights: ["Zilja tring", "zilja tringëllon"],
    newWords: [
      { word: "Zile", meaning: "sende që tingëllojnë tring-tring" },
      { word: "Sajë", meaning: "me të cilën rrëshqasim mbi dëborë" },
      { word: "Dëborë", meaning: "bora e bardhë që bie në dimër" },
    ],
    whatWeLearn: ["Dimri dhe dëbora", "Tingujt: tring, tringëllon", "Gëzimi i festave"],
    activity: "Vizato një sajë mbi dëborë me zile.",
  },
  {
    id: 33,
    title: "Babagjyshi vjen në qytet",
    palette: "apple",
    icon: "paw",
    videoUrl: "https://www.youtube.com/watch?v=PyWn2SzaDto",
    lyrics: [
      "Mbi një sajë me dre",
      "Ësht’ nisur tek ne",
      "Me një thes në dorë",
      "Po ecën nëpër borë",
      "Babagjyshi vjen në qytet!",
      "",
      "Listën plot me emra",
      "E ka futur brenda",
      "Tani erdhi koha",
      "Të gëzohen zemrat tona",
      "Babagjyshi vjen në qytet!",
      "Ai të gjithëve na ka parë",
      "A kemi qenë fëmijë të mbarë",
      "Ke kujdes se mos gabon",
      "T’verteten  nuk e tregon!",
      "Mbi një sajë me dre",
      "Ësht’ nisur tek ne",
      "Me një thes në dorë",
      "Po ecën nëpër borë",
      "Babagjyshi vjen në qytet!",
      "Ai të gjithëve na ka parë",
      "A kemi qenë fëmijë të mbarë",
      "Ke kujdes se mos gabon",
      "T’vërtetën nuk e tregon!",
      "Mbi një sajë me dre",
      "Ësht’ nisur tek ne",
      "Me një thes në dorë",
      "Po ecën nëpër borë",
      "Babagjyshi vjen në qytet!",
    ],
    highlights: ["Babagjyshi vjen në qytet"],
    newWords: [
      { word: "Babagjysh", meaning: "plaku i mirë që sjell dhurata në festa" },
      { word: "Sajë", meaning: "me të cilën ecën mbi borë" },
      { word: "Dre", meaning: "kafsha me brirë që tërheq sajën" },
    ],
    whatWeLearn: ["Festat e Vitit të Ri", "Të jemi fëmijë të mirë", "Babagjyshi dhe dhuratat"],
    activity: "Vizato Babagjyshin me sajën dhe dretë.",
  },
  {
    id: 34,
    title: "Urime, Gëzuar Festat!",
    palette: "instrument",
    icon: "heart",
    videoUrl: "https://www.youtube.com/watch?v=eKwSfnl0fFQ",
    lyrics: [
      "Urime, Gëzuar Festat!",
      "Urime, Gëzuar Festat!",
      "Urime, Gëzuar Festat!",
      "Me shumë dashuri!",
      "Për këtë Vit të Ri",
      "Të dhurojmë dashuri!",
      "Urime, Gëzuar Festat",
      "Me shumë dashuri!",
      "Të gjithë janë të gëzuar",
      "Të gjithë janë të gëzuar",
      "Të gjithë janë të gëzuar",
      "Për Vitin e Ri!",
      "Nëpër çdo shtëpi",
      "Të ketë harmoni",
      "Urime, Gëzuar Festat",
      "Me shumë dashuri!",
      "Të gjithë janë të gëzuar",
      "Të gjithë janë të gëzuar",
      "Të gjithë janë të gëzuar",
      "Për Vitin e Ri!",
      "Nëpër çdo shtëpi",
      "Të ketë harmoni",
      "Urime, Gëzuar Festat",
      "Me shumë dashuri!",
    ],
    highlights: ["Urime, Gëzuar Festat", "Me shumë dashuri"],
    newWords: [
      { word: "Urime", meaning: "fjalë që themi për të gëzuar dikë" },
      { word: "Festë", meaning: "ditë e veçantë me gëzim" },
      { word: "Vit i Ri", meaning: "fillimi i një viti të ri" },
    ],
    whatWeLearn: ["Urimet e festave", "Viti i Ri", "Gëzimi dhe dashuria"],
    activity: "Bëj një kartolinë me “Gëzuar Festat!”",
  },
  {
    id: 35,
    title: "Saja ime",
    palette: "movement",
    icon: "musical-notes",
    videoUrl: "https://www.youtube.com/watch?v=Kqoxv8OZRYg",
    lyrics: [
      "Sa më bën të lumtur",
      "Saja ime e bukur",
      "Me të fluturoj",
      "Edhe qiellin e takoj!",
      "Por me sajën s’ka mahi",
      "Ajo ecën me furi",
      "Me dy duart unë mbahem Nga ajo nuk ndahem.",
      "Sikur një shigjetë",
      "Ngjitem unë përpjetë Fëmijët më lakmojnë Sajën time e kërkojnë.",
      "Por me sajën s’ka mahi Ajo ecën me furi",
      "Me dy duart unë mbahem Nga ajo nuk ndahem.",
      "Timonin fort e mbaj Fluturoj me sajë",
      "Sikur mbi një dre",
      "Ngjitem përmbi re!",
      "Por me sajën s’ka mahi",
      "Ajo ecën me furi",
      "Me dy duart unë mbahem Nga ajo nuk ndahem.",
    ],
    highlights: ["Ajo ecën me furi", "Nga ajo nuk ndahem"],
    newWords: [
      { word: "Sajë", meaning: "me të cilën rrëshqasim mbi dëborë" },
      { word: "Timon", meaning: "me të cilin drejtojmë sajën" },
      { word: "Shigjetë", meaning: "diçka që fluturon shpejt" },
    ],
    whatWeLearn: ["Lojërat e dimrit", "Shpejt dhe ngadalë", "Të mbahemi fort për siguri"],
    activity: "Vizato veten duke rrëshqitur me sajë mbi dëborë.",
  },
  {
    id: 36,
    title: "Himni i festave",
    palette: "nature",
    icon: "happy",
    videoUrl: "https://www.youtube.com/watch?v=9hQDtIjIvnQ",
    lyrics: [
      "Zbukurojmë gjithë shtëpinë",
      "Fa-la-la-la-la-la-la-la",
      "",
      "E urojmë mirësinë",
      "La-la-la-la-la-la-la-la-la",
      "",
      "Vishemi me rroba  t’blerta",
      "Fa-la-la-la-la-la-la-la-la",
      "",
      "Dhe këndojmë këngë të vjetra",
      "La-la-la-la-la-la-la-la-la",
      "",
      "Pranë zjarrit bashkë qëndrojmë",
      "Fa-la-la-la-la-la-la-la-la",
      "",
      "Këngë të lumtura këndojmë",
      "Fa-la-la-la-la-la-la-la-la",
      "",
      "Të bashkohemi në ritëm",
      "Fa-la-la-la-la-la-la-la-la",
      "",
      "Teksa zjarri na ngroh shpirtin",
      "La-la-la-la-la-la-la-la-la",
      "",
      "Dit’ të reja po na presin",
      "Fa-la-la-la-la-la-la-la-la",
      "",
      "Vite tjera përshëndesim",
      "La-la-la-la-la-la-la-la",
      "",
      "Të festojmë të gëzuar",
      "Fa-la-la-la-la-la-la-la-la",
      "",
      "Në këtë ditë të praruar",
      "La-la-la-la-la-la-la-la-la",
    ],
    highlights: ["Fa-la-la-la-la", "La-la-la-la"],
    newWords: [
      { word: "Zbukurojmë", meaning: "bëjmë të bukur me ngjyra e gjëra" },
      { word: "Zjarr", meaning: "drita e ngrohtë që na ngroh" },
      { word: "Festë", meaning: "ditë gëzimi" },
    ],
    whatWeLearn: ["Zbukurimi për festa", "Të këndojmë bashkë", "Dimri dhe ngrohtësia e shtëpisë"],
    activity: "Zbukuro një pemë feste me vizatime me ngjyra.",
  },
]
